// SPDX-FileCopyrightText: 2026 aesc silicon
//
// SPDX-License-Identifier: CERN-OHL-W-2.0

package nafarr.blackboxes.muninn

import java.io.File

import spinal.core._

/** Tsetlin clause array (CAM) macros generated by Muninn.
  *
  * The hard macro (`muninn_tcam_<variant>_<rows>x<cols>`) comes prebuilt from the
  * muninn-macros repository; its behavioural model is used for simulation. All
  * variants share the pins and the cycle behaviour.
  * `TcamModel` is a flop-based equivalent for FPGAs.
  *
  * Cycle behaviour as seen from logic clocked on the rising edge:
  *   - write: `writeEnable`, `address` and `writeData` registered on edge k; the
  *     row holds the data from edge k + 1 on.
  *   - search: `searchEnable` and `literals` registered on edge k; `matches` is
  *     valid at the end of that cycle and must be sampled on edge k + 1. Without a
  *     search, all matches read 1.
  *   - a row written in a cycle must not be searched in the same cycle.
  */
object Tcam {

  /** Layout style of the hard macro. */
  sealed abstract class Variant(val name: String)
  object Variant {

    /** Full-custom array, optimized for area. */
    case object Dense extends Variant("dense")

    /** Full-custom array, optimized for timing. */
    case object Speed extends Variant("speed")

    /** Array built mostly from standard cells. */
    case object Conservative extends Variant("conservative")
  }

  case class Parameter(
      rows: Int,
      cols: Int,
      hard: Boolean = true,
      variant: Variant = Variant.Dense
  ) {
    require(rows >= 16 && rows % 2 == 0, "rows: even and at least 16")
    require(cols >= 2, "at least two literal columns")
    val addressBits = Math.max(4, log2Up(rows))
    def name = s"muninn_tcam_${variant.name}_${rows}x${cols}"
  }

  case class Io(p: Parameter) extends Bundle {
    val searchEnable = in(Bool())
    val literals = in(Bits(p.cols bits))
    val writeEnable = in(Bool())
    val address = in(UInt(p.addressBits bits))
    val writeData = in(Bits(p.cols bits))
    val matches = out(Bits(p.rows bits))
  }

  /** Directory of a released macro for `pdk` (default: `PDK`), if present. */
  def macroDir(
      p: Parameter,
      pdk: String = sys.env.getOrElse("PDK", "ihp-sg13g2")
  ): Option[String] = {
    val repo = sys.env.getOrElse(
      "MUNINN_MACROS",
      sys.env.getOrElse("NAFARR_BASE", ".") + "/ext/muninn-macros"
    )
    val dir = new File(s"$repo/$pdk/${p.name}")
    if (dir.isDirectory) Some(dir.getPath) else None
  }

  /** Behavioural model of a released macro for `pdk` (default: `PDK`), if present. */
  def modelPath(
      p: Parameter,
      pdk: String = sys.env.getOrElse("PDK", "ihp-sg13g2")
  ): Option[String] = {
    macroDir(p, pdk).map(dir => s"$dir/${p.name}.v").filter(new File(_).isFile)
  }

  /** IO of the hard macro, or of the flop-based model when `p.hard` is false. */
  def apply(p: Parameter): Io = if (p.hard) MuninnTcam(p).io else TcamModel(p).io
}

case class MuninnTcam(p: Tcam.Parameter) extends Component {
  val io = Tcam.Io(p)

  val tcam = new BlackBox {
    setDefinitionName(p.name)
    val CLK = in(Bool())
    val SEARCH_EN = in(Bool())
    val WE = in(Bool())
    val A = in(Bits(p.addressBits bits))
    val LIT = in(Bits(p.cols bits))
    val WDATA = in(Bits(p.cols bits))
    val MATCH = out(Bits(p.rows bits))

    mapCurrentClockDomain(CLK)
    Tcam.modelPath(p).foreach(addRTLPath(_))
  }
  tcam.setName("tcam")

  tcam.SEARCH_EN := io.searchEnable
  tcam.WE := io.writeEnable
  tcam.A := io.address.asBits
  tcam.LIT := io.literals
  tcam.WDATA := io.writeData
  io.matches := tcam.MATCH
}

case class TcamModel(p: Tcam.Parameter) extends Component {
  val io = Tcam.Io(p)

  val rows = Vec(Reg(Bits(p.cols bits)) init (0), p.rows)
  for (r <- 0 until p.rows) {
    when(io.writeEnable && io.address === r) {
      rows(r) := io.writeData
    }
  }
  // a clause matches when no included literal is 0
  val hits = Cat(rows.map(row => !(row & ~io.literals).orR)) // Cat: first element is the LSB
  io.matches := io.searchEnable ? hits | B(p.rows bits, default -> True)
}
